/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/hero_model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hero_model.glb')
  return (
    <group {...props} dispose={null}>
       <directionalLight color="purple" position={[-12, 10, 10]} />
      <directionalLight color="green" position={[-5, 0, 7]} />
      {/* <directionalLight color="#5CE4CF" position={[20, -7, 10]} /> */}
      {/* <directionalLight color="#676b7e" position={[-5, 5, 7]} /> */}
      <directionalLight color="#757a94" position={[-1.5, -3, 7]} />
      {/* <pointLight color="purple" position={[5, 0, 5]} /> */}
      <directionalLight color="#757a94" position={[8, 8, 10]} />
      <group position={[0, 0.144, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.089}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.619, -0.017]} rotation={[0.123, 0, 0]}>
            <mesh geometry={nodes.keyboard_Key_0.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.keyboard_Keyboard_0.geometry} material={materials['Keyboard.001']} />
          </group>
          <group position={[-15.094, 1.498, 2.822]} rotation={[0.123, 0, 0]}>
            <mesh geometry={nodes.keys_Key_0.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.keys_Key_1.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.keys_Key_2.geometry} material={materials['material.001']} />
          </group>
          <mesh geometry={nodes.emissive_Key_0.geometry} material={materials['material.001']} position={[-15.094, 1.671, 2.843]} rotation={[0.123, 0, 0]} />
          <mesh geometry={nodes.legs_Keyboard_0.geometry} material={materials['Keyboard.001']} position={[0, 0.921, -4.98]} rotation={[2.487, 0, 0]} />
        </group>
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Cube Black']} rotation={[0, 1.571, 0]} scale={[1.205, 0.149, 2.094]} />



      <group position={[0, 0.144, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.089}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group position={[0, 1.619, -0.017]} rotation={[0.123, 0, 0]}>
          <mesh geometry={nodes.keyboard_Key_0.geometry} material={materials['material.001']} />
          <mesh geometry={nodes.keyboard_Keyboard_0.geometry} material={materials['Keyboard.001']} />
        </group>
        <group position={[-15.094, 1.498, 2.822]} rotation={[0.123, 0, 0]}>
          <mesh ref={key0} geometry={nodes.keys_Key_0.geometry} material={materials['material.001']} />
          <mesh ref={key1} geometry={nodes.keys_Key_1.geometry} material={materials['material.001']} />
          <mesh ref={key2} geometry={nodes.keys_Key_2.geometry} material={materials['material.001']} />
        </group>
        <mesh geometry={nodes.emissive_Key_0.geometry} material={materials['material.001']} position={[-15.094, 1.671, 2.843]} rotation={[0.123, 0, 0]} />
        <mesh geometry={nodes.legs_Keyboard_0.geometry} material={materials['Keyboard.001']} position={[0, 0.921, -4.98]} rotation={[2.487, 0, 0]} />
      </group>
    </group>
    <mesh geometry={nodes.Cube002.geometry} material={materials['Cube Black']} rotation={[0, 1.571, 0]} scale={[1.205, 0.149, 2.094]} />

    </group>
  )
}

useGLTF.preload('/hero_model.glb')
