/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/screen.glb --k
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/screen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Clear Tab']} position={[-0.178, 3.714, 0.677]} rotation={[0, Math.PI / 2, 0]} scale={[0.306, 0.015, 0.49]} />
      <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Rough Glass']} position={[-0.177, 3.714, 0.685]} rotation={[Math.PI, 0, Math.PI]} scale={[0.453, 0.007, 0.147]} />
      <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Emissive Glass']} position={[-0.178, 3.714, 0.677]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.315, 0, -0.495]} />
    </group>
  )
}

useGLTF.preload('/screen.glb')
