import Head from 'next/head'
import Image from 'next/image'
import { Canvas } from "@react-three/fiber";
// import { Background } from "../components/global/Background";
import { Bg } from "../components/global/Bg";
import { Scroll, ScrollControls } from "@react-three/drei";
// import { Interface } from "./components/Interface";
// import { ScrollManager } from "./components/ScrollManager";
import { Navbar } from "../components/global/Navbar";
import { useEffect, useState } from "react";
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MainLayout from '@/components/global/MainLayout';
import { Interface } from '@/components/home/Interface';

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Voltrox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.jpeg" />
      </Head>
      <MainLayout>
        <Interface />
      </MainLayout>
    </>
  )
}

export async function getServerSideProps() {
  // Disable SSR by returning an empty object
  return {
    props: {},
  };
}
