/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/bg.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bg(props) {

  const slab = useGLTF('./models/bg.glb');

  return (
    <mesh>
      {/* <ambientLight intensity={0.3} /> */}
      <directionalLight color="purple" position={[-12, 10, 10]} />
      <directionalLight color="green" position={[-5, 0, 7]} />
      {/* <directionalLight color="#5CE4CF" position={[20, -7, 10]} /> */}
      {/* <directionalLight color="#676b7e" position={[-5, 5, 7]} /> */}
      <directionalLight color="#757a94" position={[-1.5, -3, 7]} />
      {/* <pointLight color="purple" position={[5, 0, 5]} /> */}
      <directionalLight color="#757a94" position={[8, 8, 10]} />
      {/* <directionalLight color="aqua" position={[9, -16, 12]} /> */}
      <primitive
        object={slab.scene}
        scale={[2, 2, 2]}
        position={[0, 1, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </mesh>
  );
}

useGLTF.preload('./models/bg.glb')
