/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/office5.glb --k
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Office (props) {
  const { nodes, materials } = useGLTF('./models/office.glb')
  return (
    <group {...props} dispose={null} position={[-1.2, -0.25, 1]} rotation={[Math.PI / 10, Math.PI / 8, -Math.PI / 20]} scale={0.854}>
      <group name="Sketchfab_model" position={[-0.264, 0.673, 2.458]} rotation={[-1.541, -0.032, 0.248]} scale={0.013}>
        <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Box26" position={[16.037, 50.997, -18.414]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.203, 0.243, 0.136]}>
            <mesh name="MaterialFBXASC032FBXASC0354_ncl1_1" geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} position={[-22.546, 23.15, -0.416]} />
          </group>
          <group name="desk" position={[40.574, 19.542, 8.922]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Box08" position={[-60.47, -35.496, -18.901]} scale={[0.044, 0.063, 0.212]}>
              <mesh name="MaterialFBXASC032FBXASC0353006" geometry={nodes.MaterialFBXASC032FBXASC0353006.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[0, -0.001, 0]} />
            </group>
            <mesh name="MaterialFBXASC032FBXASC0353" geometry={nodes.MaterialFBXASC032FBXASC0353.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-36.625, -67.542, -31.299]} scale={[1.414, 1, 1.702]} />
            <mesh name="MaterialFBXASC032FBXASC0353001" geometry={nodes.MaterialFBXASC032FBXASC0353001.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 0.892, -26.24]} scale={[0.074, 2.084, 0.257]} />
            <mesh name="MaterialFBXASC032FBXASC0353004" geometry={nodes.MaterialFBXASC032FBXASC0353004.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 36.798, -18.901]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353002" geometry={nodes.MaterialFBXASC032FBXASC0353002.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 0.892, -14.175]} scale={[0.074, 1.859, 0.727]} />
            <mesh name="MaterialFBXASC032FBXASC0353003" geometry={nodes.MaterialFBXASC032FBXASC0353003.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 0.892, 12.469]} scale={[0.074, 2.084, 0.257]} />
            <mesh name="MaterialFBXASC032FBXASC0353005" geometry={nodes.MaterialFBXASC032FBXASC0353005.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 30.411, -18.901]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353007" geometry={nodes.MaterialFBXASC032FBXASC0353007.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -29.109, -18.901]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353008" geometry={nodes.MaterialFBXASC032FBXASC0353008.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -35.496, 7.242]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353009" geometry={nodes.MaterialFBXASC032FBXASC0353009.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -29.109, 7.242]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353010" geometry={nodes.MaterialFBXASC032FBXASC0353010.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 30.169, 7.242]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353011" geometry={nodes.MaterialFBXASC032FBXASC0353011.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 36.556, 7.242]} scale={[0.044, 0.063, 0.212]} />
            <mesh name="MaterialFBXASC032FBXASC0353012" geometry={nodes.MaterialFBXASC032FBXASC0353012.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 43.392, 3.392]} scale={[0.044, 0.217, 0.076]} />
            <mesh name="MaterialFBXASC032FBXASC0353013" geometry={nodes.MaterialFBXASC032FBXASC0353013.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, 43.392, -11.557]} scale={[0.044, 0.217, 0.076]} />
            <mesh name="MaterialFBXASC032FBXASC0353014" geometry={nodes.MaterialFBXASC032FBXASC0353014.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -41.96, -11.557]} scale={[0.044, 0.217, 0.076]} />
            <mesh name="MaterialFBXASC032FBXASC0353015" geometry={nodes.MaterialFBXASC032FBXASC0353015.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-60.47, -41.96, 3.392]} scale={[0.044, 0.217, 0.076]} />
            <mesh name="MaterialFBXASC032FBXASC0353017" geometry={nodes.MaterialFBXASC032FBXASC0353017.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-21.89, 0, 29.697]} scale={[1.414, 1.378, 0.174]} />
            <mesh name="MaterialFBXASC032FBXASC0353023" geometry={nodes.MaterialFBXASC032FBXASC0353023.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[30.497, 72.436, -31.299]} scale={[1.933, 0.823, 1.189]} />
            <mesh name="MaterialFBXASC032FBXASC0353024" geometry={nodes.MaterialFBXASC032FBXASC0353024.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[49.384, 50.312, -25.213]} scale={[0.754, 0.448, 1.275]} />
            <mesh name="MaterialFBXASC032FBXASC0353025" geometry={nodes.MaterialFBXASC032FBXASC0353025.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[49.384, 50.312, -10.65]} scale={[0.754, 0.448, 1.275]} />
            <mesh name="MaterialFBXASC032FBXASC0353026" geometry={nodes.MaterialFBXASC032FBXASC0353026.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[11.136, 50.312, -10.65]} scale={[0.754, 0.448, 1.275]} />
            <mesh name="MaterialFBXASC032FBXASC0353027" geometry={nodes.MaterialFBXASC032FBXASC0353027.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[11.136, 50.312, -25.213]} scale={[0.754, 0.448, 1.275]} />
            <mesh name="MaterialFBXASC032FBXASC0353028" geometry={nodes.MaterialFBXASC032FBXASC0353028.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-36.625, 68.886, -31.299]} scale={[1.414, 1, 1.702]} />
            <mesh name="MaterialFBXASC032FBXASC0353016" geometry={nodes.MaterialFBXASC032FBXASC0353016.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-53.04, -68.976, 14.92]} scale={[0.247, 0.247, 0.715]} />
            <mesh name="MaterialFBXASC032FBXASC0353018" geometry={nodes.MaterialFBXASC032FBXASC0353018.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-53.04, 71.314, 14.921]} scale={[0.247, 0.247, 0.715]} />
            <mesh name="MaterialFBXASC032FBXASC0353019" geometry={nodes.MaterialFBXASC032FBXASC0353019.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.405, 80.502, 14.921]} scale={[0.247, 0.247, 0.715]} />
            <mesh name="MaterialFBXASC032FBXASC0353020" geometry={nodes.MaterialFBXASC032FBXASC0353020.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.405, -81.085, 14.921]} scale={[0.247, 0.247, 0.715]} />
            <mesh name="MaterialFBXASC032FBXASC0353021" geometry={nodes.MaterialFBXASC032FBXASC0353021.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.405, -53.294, 14.92]} scale={[0.247, 0.247, 0.715]} />
            <mesh name="MaterialFBXASC032FBXASC0353022" geometry={nodes.MaterialFBXASC032FBXASC0353022.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[-29.405, 54.493, 14.921]} scale={[0.247, 0.247, 0.715]} />
          </group>
          <group name="SANDALI" position={[69.022, 39.481, 21.318]} rotation={[-Math.PI / 2, 0, 0]} scale={1.565}>
            <mesh name="MaterialFBXASC032FBXASC03538" geometry={nodes.MaterialFBXASC032FBXASC03538.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[-0.223, -0.54, -8.012]} scale={[0.284, 0.322, 0.284]} />
            <mesh name="MaterialFBXASC032FBXASC03538003" geometry={nodes.MaterialFBXASC032FBXASC03538003.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[14.432, -0.528, -6.251]} rotation={[0, 0.105, 0]} scale={[0.06, 0.368, 4.143]} />
            <mesh name="MaterialFBXASC032FBXASC03538002" geometry={nodes.MaterialFBXASC032FBXASC03538002.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[-1.664, 15.271, 5.316]} scale={0.444} />
            <mesh name="MaterialFBXASC032FBXASC03538001" geometry={nodes.MaterialFBXASC032FBXASC03538001.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[-1.664, -17.269, 5.316]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.444} />
            <mesh name="MaterialFBXASC032FBXASC03538004" geometry={nodes.MaterialFBXASC032FBXASC03538004.geometry} material={materials.MaterialFBXASC032FBXASC03538} position={[20.742, 0.194, 5.401]} rotation={[0, -1.192, 0]} scale={[0.405, 0.405, 0.17]} />
          </group>
          <mesh name="MaterialFBXASC032FBXASC0354" geometry={nodes.MaterialFBXASC032FBXASC0354.geometry} material={materials.MaterialFBXASC032FBXASC0354} position={[-22.588, 88.167, 28.596]} rotation={[-Math.PI / 2, -0.256, -Math.PI / 2]} scale={[0.261, 0.458, 0.458]} />
          <mesh name="MaterialFBXASC032FBXASC0354_ncl1_1002" geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1002.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} position={[6.864, 51.118, -34.455]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.514, 1.18, 0.514]} />
          <mesh name="MaterialFBXASC032FBXASC0352" geometry={nodes.MaterialFBXASC032FBXASC0352.geometry} material={materials.MaterialFBXASC032FBXASC0352} position={[76.12, 26.409, -66.145]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.514, 0.514, 0.363]} />
          <mesh name="MaterialFBXASC032FBXASC0354_ncl1_1001" geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1001.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} position={[14.69, 51.403, 11.988]} rotation={[-Math.PI / 2, 0.147, -Math.PI]} scale={[0.53, 0.715, 0.715]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/office.glb')
