/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/office2.glb -K -k
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Adeyemi } from './Adeyemi'

export function Office(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/office3.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group {...props} dispose={null} position={[-1.2, -0.25, 1]} rotation={[Math.PI / 10, Math.PI / 8, -Math.PI / 20]} scale={0.854}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-0.264, 0.673, 2.458]} rotation={[-1.541, -0.032, 0.248]} scale={0.013}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Box01" position={[-22.588, 88.167, 28.596]} rotation={[-Math.PI / 2, -0.256, -Math.PI / 2]} scale={[0.261, 0.458, 0.458]}>
              <mesh name="MaterialFBXASC032FBXASC0354" geometry={nodes.MaterialFBXASC032FBXASC0354.geometry} material={materials.MaterialFBXASC032FBXASC0354} />
            </group>
            <group name="Box03" position={[6.864, 51.118, -34.455]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.514, 1.18, 0.514]}>
              <mesh name="MaterialFBXASC032FBXASC0354_ncl1_1002" geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1002.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} />
            </group>
            <group name="Box04" position={[76.12, 26.409, -66.145]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.514, 0.514, 0.363]}>
              <mesh name="MaterialFBXASC032FBXASC0352" geometry={nodes.MaterialFBXASC032FBXASC0352.geometry} material={materials.MaterialFBXASC032FBXASC0352} />
            </group>
            <group name="Box24" position={[14.69, 51.403, 11.988]} rotation={[-Math.PI / 2, 0.147, -Math.PI]} scale={[0.53, 0.715, 0.715]}>
              <mesh name="MaterialFBXASC032FBXASC0354_ncl1_1001" geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1001.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} />
            </group>
            <group name="Box26" position={[16.037, 50.997, -18.414]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.203, 0.243, 0.136]}>
              <mesh name="MaterialFBXASC032FBXASC0354_ncl1_1" geometry={nodes.MaterialFBXASC032FBXASC0354_ncl1_1.geometry} material={materials.MaterialFBXASC032FBXASC0354_ncl1_1} />
            </group>
            <group name="desk" position={[40.574, 19.542, 8.922]} rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Box02_ncl1_1" position={[-36.625, -67.542, -31.299]} scale={[1.414, 1, 1.702]}>
                <mesh name="MaterialFBXASC032FBXASC0353" geometry={nodes.MaterialFBXASC032FBXASC0353.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box03_ncl1_2" position={[-60.47, 0.892, -26.24]} scale={[0.074, 2.084, 0.257]}>
                <mesh name="MaterialFBXASC032FBXASC0353001" geometry={nodes.MaterialFBXASC032FBXASC0353001.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box04_ncl1_2" position={[-60.47, 36.798, -18.901]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353004" geometry={nodes.MaterialFBXASC032FBXASC0353004.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box05" position={[-60.47, 0.892, -14.175]} scale={[0.074, 1.859, 0.727]}>
                <mesh name="MaterialFBXASC032FBXASC0353002" geometry={nodes.MaterialFBXASC032FBXASC0353002.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box06" position={[-60.47, 0.892, 12.469]} scale={[0.074, 2.084, 0.257]}>
                <mesh name="MaterialFBXASC032FBXASC0353003" geometry={nodes.MaterialFBXASC032FBXASC0353003.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box07" position={[-60.47, 30.411, -18.901]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353005" geometry={nodes.MaterialFBXASC032FBXASC0353005.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box08" position={[-60.47, -35.496, -18.901]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353006" geometry={nodes.MaterialFBXASC032FBXASC0353006.geometry} material={materials.MaterialFBXASC032FBXASC0353} position={[0, -0.001, 0]} />
              </group>
              <group name="Box09" position={[-60.47, -29.109, -18.901]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353007" geometry={nodes.MaterialFBXASC032FBXASC0353007.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box10" position={[-60.47, -35.496, 7.242]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353008" geometry={nodes.MaterialFBXASC032FBXASC0353008.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box11" position={[-60.47, -29.109, 7.242]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353009" geometry={nodes.MaterialFBXASC032FBXASC0353009.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box12" position={[-60.47, 30.169, 7.242]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353010" geometry={nodes.MaterialFBXASC032FBXASC0353010.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box13" position={[-60.47, 36.556, 7.242]} scale={[0.044, 0.063, 0.212]}>
                <mesh name="MaterialFBXASC032FBXASC0353011" geometry={nodes.MaterialFBXASC032FBXASC0353011.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box14" position={[-60.47, 43.392, 3.392]} scale={[0.044, 0.217, 0.076]}>
                <mesh name="MaterialFBXASC032FBXASC0353012" geometry={nodes.MaterialFBXASC032FBXASC0353012.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box15" position={[-60.47, 43.392, -11.557]} scale={[0.044, 0.217, 0.076]}>
                <mesh name="MaterialFBXASC032FBXASC0353013" geometry={nodes.MaterialFBXASC032FBXASC0353013.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box16" position={[-60.47, -41.96, -11.557]} scale={[0.044, 0.217, 0.076]}>
                <mesh name="MaterialFBXASC032FBXASC0353014" geometry={nodes.MaterialFBXASC032FBXASC0353014.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box17" position={[-60.47, -41.96, 3.392]} scale={[0.044, 0.217, 0.076]}>
                <mesh name="MaterialFBXASC032FBXASC0353015" geometry={nodes.MaterialFBXASC032FBXASC0353015.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box18" position={[-21.89, 0, 29.697]} scale={[1.414, 1.378, 0.174]}>
                <mesh name="MaterialFBXASC032FBXASC0353017" geometry={nodes.MaterialFBXASC032FBXASC0353017.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box19" position={[30.497, 72.436, -31.299]} scale={[1.933, 0.823, 1.189]}>
                <mesh name="MaterialFBXASC032FBXASC0353023" geometry={nodes.MaterialFBXASC032FBXASC0353023.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box20" position={[49.384, 50.312, -25.213]} scale={[0.754, 0.448, 1.275]}>
                <mesh name="MaterialFBXASC032FBXASC0353024" geometry={nodes.MaterialFBXASC032FBXASC0353024.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box21" position={[49.384, 50.312, -10.65]} scale={[0.754, 0.448, 1.275]}>
                <mesh name="MaterialFBXASC032FBXASC0353025" geometry={nodes.MaterialFBXASC032FBXASC0353025.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box22" position={[11.136, 50.312, -10.65]} scale={[0.754, 0.448, 1.275]}>
                <mesh name="MaterialFBXASC032FBXASC0353026" geometry={nodes.MaterialFBXASC032FBXASC0353026.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box23" position={[11.136, 50.312, -25.213]} scale={[0.754, 0.448, 1.275]}>
                <mesh name="MaterialFBXASC032FBXASC0353027" geometry={nodes.MaterialFBXASC032FBXASC0353027.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Box25" position={[-36.625, 68.886, -31.299]} scale={[1.414, 1, 1.702]}>
                <mesh name="MaterialFBXASC032FBXASC0353028" geometry={nodes.MaterialFBXASC032FBXASC0353028.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Cylinder01" position={[-53.04, -68.976, 14.92]} scale={[0.247, 0.247, 0.715]}>
                <mesh name="MaterialFBXASC032FBXASC0353016" geometry={nodes.MaterialFBXASC032FBXASC0353016.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Cylinder02" position={[-53.04, 71.314, 14.921]} scale={[0.247, 0.247, 0.715]}>
                <mesh name="MaterialFBXASC032FBXASC0353018" geometry={nodes.MaterialFBXASC032FBXASC0353018.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Cylinder03" position={[-29.405, 80.502, 14.921]} scale={[0.247, 0.247, 0.715]}>
                <mesh name="MaterialFBXASC032FBXASC0353019" geometry={nodes.MaterialFBXASC032FBXASC0353019.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Cylinder04" position={[-29.405, -81.085, 14.921]} scale={[0.247, 0.247, 0.715]}>
                <mesh name="MaterialFBXASC032FBXASC0353020" geometry={nodes.MaterialFBXASC032FBXASC0353020.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Cylinder05" position={[-29.405, -53.294, 14.92]} scale={[0.247, 0.247, 0.715]}>
                <mesh name="MaterialFBXASC032FBXASC0353021" geometry={nodes.MaterialFBXASC032FBXASC0353021.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
              <group name="Cylinder06" position={[-29.405, 54.493, 14.921]} scale={[0.247, 0.247, 0.715]}>
                <mesh name="MaterialFBXASC032FBXASC0353022" geometry={nodes.MaterialFBXASC032FBXASC0353022.geometry} material={materials.MaterialFBXASC032FBXASC0353} />
              </group>
            </group>
            <group name="SANDALI" position={[69.022, 39.481, 21.318]} rotation={[-Math.PI / 2, 0, 0]} scale={1.565}>
              <group name="Box01_ncl1_1" position={[-0.223, -0.54, -8.012]} scale={[0.284, 0.322, 0.284]}>
                <mesh name="MaterialFBXASC032FBXASC03538" geometry={nodes.MaterialFBXASC032FBXASC03538.geometry} material={materials.MaterialFBXASC032FBXASC03538} />
              </group>
              <group name="Box02" position={[14.432, -0.528, -6.251]} rotation={[0, 0.105, 0]} scale={[0.06, 0.368, 4.143]}>
                <mesh name="MaterialFBXASC032FBXASC03538003" geometry={nodes.MaterialFBXASC032FBXASC03538003.geometry} material={materials.MaterialFBXASC032FBXASC03538} />
              </group>
              <group name="Box03_ncl1_1" position={[-1.664, 15.271, 5.316]} scale={0.444}>
                <mesh name="MaterialFBXASC032FBXASC03538002" geometry={nodes.MaterialFBXASC032FBXASC03538002.geometry} material={materials.MaterialFBXASC032FBXASC03538} />
              </group>
              <group name="Box04_ncl1_1" position={[-1.664, -17.269, 5.316]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.444}>
                <mesh name="MaterialFBXASC032FBXASC03538001" geometry={nodes.MaterialFBXASC032FBXASC03538001.geometry} material={materials.MaterialFBXASC032FBXASC03538} />
              </group>
              <group name="ChamferBox02" position={[20.742, 0.194, 5.401]} rotation={[0, -1.192, 0]} scale={[0.405, 0.405, 0.17]}>
                <mesh name="MaterialFBXASC032FBXASC03538004" geometry={nodes.MaterialFBXASC032FBXASC03538004.geometry} material={materials.MaterialFBXASC032FBXASC03538} />
              </group>
            </group>
          </group>
        </group>
        <group name="Empty" position={[-2.749, 2.041, 3.11]} rotation={[0, -1.468, 0]}>
          <group name="Armature" position={[-0.246, -1.361, -3.415]}>
            <group name="Hips" position={[0, 1.019, 0.01]} rotation={[0.032, 0, 0]}>
              <group name="Spine" position={[0, 0.098, 0]} rotation={[-0.137, 0, 0]}>
                <group name="Spine1" position={[0, 0.13, 0]} rotation={[-0.064, 0, 0]}>
                  <group name="Spine2" position={[0, 0.122, 0]} rotation={[0.094, 0, 0]}>
                    <group name="Neck" position={[0, 0.156, 0]} rotation={[0.409, 0, 0]}>
                      <group name="Head" position={[0, 0.123, 0]} rotation={[-0.327, 0, 0]}>
                        <group name="HeadTop_End" position={[0, 0.226, 0.037]} rotation={[-0.007, 0, 0]}>
                          <group name="HeadTop_End_end" position={[0, 0.124, 0]} />
                        </group>
                        <group name="LeftEye" position={[0.03, 0.088, 0.082]} rotation={[-0.007, 0, 0]}>
                          <group name="LeftEye_end" position={[0, 0.124, 0]} />
                        </group>
                        <group name="RightEye" position={[-0.03, 0.088, 0.082]} rotation={[-0.007, 0, 0]}>
                          <group name="RightEye_end" position={[0, 0.124, 0]} />
                        </group>
                      </group>
                    </group>
                    <group name="LeftShoulder" position={[0.047, 0.141, -0.006]} rotation={[1.56, -0.04, -1.58]}>
                      <group name="LeftArm" position={[0, 0.119, 0]} rotation={[0.998, 0.019, -0.144]}>
                        <group name="LeftForeArm" position={[0, 0.285, 0]} rotation={[-0.107, 0.023, 0.447]}>
                          <group name="LeftHand" position={[0, 0.252, 0]} rotation={[0.094, 0.076, -0.041]}>
                            <group name="LeftHandThumb1" position={[-0.032, 0.026, 0.005]} rotation={[0.316, 0.122, 0.849]}>
                              <group name="LeftHandThumb2" position={[0, 0.041, 0]} rotation={[0.061, -0.169, -0.502]}>
                                <group name="LeftHandThumb3" position={[0, 0.03, 0]} rotation={[0.015, -0.051, -0.169]}>
                                  <group name="LeftHandThumb4" position={[0, 0.035, 0]} rotation={[0.027, 0.105, -0.015]}>
                                    <group name="LeftHandThumb4_end" position={[0, 0.035, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="LeftHandIndex1" position={[-0.035, 0.097, -0.007]} rotation={[0.189, -0.089, 0.152]}>
                              <group name="LeftHandIndex2" position={[0, 0.045, 0]} rotation={[0.19, -0.007, 0.052]}>
                                <group name="LeftHandIndex3" position={[0, 0.028, 0]} rotation={[0.167, -0.155, -0.03]}>
                                  <group name="LeftHandIndex4" position={[0, 0.034, 0]} rotation={[0.091, 0.113, -0.019]}>
                                    <group name="LeftHandIndex4_end" position={[0, 0.034, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="LeftHandMiddle1" position={[-0.009, 0.1, -0.003]} rotation={[0.08, -0.134, 0.036]}>
                              <group name="LeftHandMiddle2" position={[0, 0.046, 0]} rotation={[0.256, -0.008, 0.088]}>
                                <group name="LeftHandMiddle3" position={[0, 0.035, 0]} rotation={[0.405, -0.062, -0.076]}>
                                  <group name="LeftHandMiddle4" position={[0, 0.035, 0]} rotation={[0.048, 0.045, -0.004]}>
                                    <group name="LeftHandMiddle4_end" position={[0, 0.035, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="LeftHandRing1" position={[0.015, 0.096, 0.002]} rotation={[0.122, -0.117, -0.109]}>
                              <group name="LeftHandRing2" position={[0, 0.042, 0]} rotation={[0.376, -0.015, 0.096]}>
                                <group name="LeftHandRing3" position={[0, 0.036, 0]} rotation={[0.078, -0.011, 0.004]}>
                                  <group name="LeftHandRing4" position={[0, 0.03, 0]} rotation={[0.014, -0.014, 0.044]}>
                                    <group name="LeftHandRing4_end" position={[0, 0.03, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="LeftHandPinky1" position={[0.039, 0.09, 0.011]} rotation={[0.176, -0.171, -0.299]}>
                              <group name="LeftHandPinky2" position={[0, 0.028, 0]} rotation={[0.287, -0.405, 0.182]}>
                                <group name="LeftHandPinky3" position={[0, 0.022, 0]} rotation={[0.246, -0.021, 0.027]}>
                                  <group name="LeftHandPinky4" position={[0, 0.026, 0]} rotation={[0.283, 0.204, -0.054]}>
                                    <group name="LeftHandPinky4_end" position={[0, 0.026, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="RightShoulder" position={[-0.047, 0.141, -0.006]} rotation={[1.56, 0.04, 1.58]}>
                      <group name="RightArm" position={[0, 0.119, 0]} rotation={[0.998, -0.019, 0.144]}>
                        <group name="RightForeArm" position={[0, 0.285, 0]} rotation={[-0.107, -0.023, -0.447]}>
                          <group name="RightHand" position={[0, 0.252, 0]} rotation={[0.094, -0.076, 0.041]}>
                            <group name="RightHandThumb1" position={[0.032, 0.026, 0.005]} rotation={[0.316, -0.122, -0.849]}>
                              <group name="RightHandThumb2" position={[0, 0.041, 0]} rotation={[0.061, 0.169, 0.502]}>
                                <group name="RightHandThumb3" position={[0, 0.03, 0]} rotation={[0.015, 0.051, 0.169]}>
                                  <group name="RightHandThumb4" position={[0, 0.035, 0]} rotation={[0.027, -0.105, 0.015]}>
                                    <group name="RightHandThumb4_end" position={[0, 0.035, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="RightHandIndex1" position={[0.035, 0.097, -0.007]} rotation={[0.189, 0.089, -0.152]}>
                              <group name="RightHandIndex2" position={[0, 0.045, 0]} rotation={[0.19, 0.007, -0.052]}>
                                <group name="RightHandIndex3" position={[0, 0.028, 0]} rotation={[0.167, 0.155, 0.03]}>
                                  <group name="RightHandIndex4" position={[0, 0.034, 0]} rotation={[0.091, -0.113, 0.019]}>
                                    <group name="RightHandIndex4_end" position={[0, 0.034, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="RightHandMiddle1" position={[0.009, 0.1, -0.003]} rotation={[0.08, 0.134, -0.036]}>
                              <group name="RightHandMiddle2" position={[0, 0.046, 0]} rotation={[0.256, 0.008, -0.088]}>
                                <group name="RightHandMiddle3" position={[0, 0.035, 0]} rotation={[0.405, 0.062, 0.076]}>
                                  <group name="RightHandMiddle4" position={[0, 0.035, 0]} rotation={[0.048, -0.045, 0.004]}>
                                    <group name="RightHandMiddle4_end" position={[0, 0.035, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="RightHandRing1" position={[-0.015, 0.096, 0.002]} rotation={[0.122, 0.117, 0.109]}>
                              <group name="RightHandRing2" position={[0, 0.042, 0]} rotation={[0.376, 0.015, -0.096]}>
                                <group name="RightHandRing3" position={[0, 0.036, 0]} rotation={[0.078, 0.011, -0.004]}>
                                  <group name="RightHandRing4" position={[0, 0.03, 0]} rotation={[0.014, 0.014, -0.044]}>
                                    <group name="RightHandRing4_end" position={[0, 0.03, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                            <group name="RightHandPinky1" position={[-0.039, 0.09, 0.011]} rotation={[0.176, 0.171, 0.299]}>
                              <group name="RightHandPinky2" position={[0, 0.028, 0]} rotation={[0.287, 0.405, -0.182]}>
                                <group name="RightHandPinky3" position={[0, 0.022, 0]} rotation={[0.246, 0.021, -0.027]}>
                                  <group name="RightHandPinky4" position={[0, 0.026, 0]} rotation={[0.283, -0.204, 0.054]}>
                                    <group name="RightHandPinky4_end" position={[0, 0.026, 0]} />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="LeftUpLeg" position={[0.095, 0.005, -0.003]} rotation={[-0.019, -0.003, -3.076]}>
                <group name="LeftLeg" position={[0, 0.458, 0]} rotation={[-0.083, 0, -0.006]}>
                  <group name="LeftFoot" position={[0, 0.444, 0]} rotation={[1.065, 0.03, -0.014]}>
                    <group name="LeftToeBase" position={[0, 0.149, 0]} rotation={[0.546, -0.074, 0.059]}>
                      <group name="LeftToe_End" position={[0, 0.099, 0]} rotation={[-0.546, 1.542, 0.581]}>
                        <group name="LeftToe_End_end" position={[0, 0.099, 0]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="RightUpLeg" position={[-0.095, 0.005, -0.003]} rotation={[-0.019, 0.004, 3.076]}>
                <group name="RightLeg" position={[0, 0.458, 0]} rotation={[-0.083, 0, 0.006]}>
                  <group name="RightFoot" position={[0, 0.444, 0]} rotation={[1.065, -0.03, 0.014]}>
                    <group name="RightToeBase" position={[0, 0.149, 0]} rotation={[0.546, 0.074, -0.059]}>
                      <group name="RightToe_End" position={[0, 0.099, 0]} rotation={[-0.547, -1.542, -0.582]}>
                        <group name="RightToe_End_end" position={[0, 0.099, 0]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <mesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Glasses" geometry={nodes.Wolf3D_Glasses.geometry} material={materials['Wolf3D_Glasses.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.002']} position={[-0.246, -1.361, -3.415]} />
          <mesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.002']} position={[-0.246, -1.361, -3.415]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/office3.glb')
