/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/about_hero.glb --k
*/

import React, { useRef } from 'react'
import { useFrame } from "@react-three/fiber"
import { useGLTF } from '@react-three/drei'

export function AboutHero(props) {
  const { nodes, materials } = useGLTF('./models/about_hero.glb')

  const cube014Ref = useRef()
  const cube032Ref = useRef()
  const cube058Ref = useRef()
  const text005Ref = useRef()
  const text007Ref = useRef()
  const cube059Ref = useRef()
  const cube033Ref = useRef()

  // Animation properties
  const amplitude = 1.5
  const frequency = 0.1

  useFrame((state, delta) => {
    // Calculate the new position and rotation for each mesh
    const time = state.clock.getElapsedTime()

    // Cube014 movement
    cube014Ref.current.rotation.y += 0.04

    // Cube032 movement
    cube032Ref.current.rotation.y += 0.04

    // Cube058 movement
    cube058Ref.current.rotation.y += 0.04

    // Text007 movement
    text007Ref.current.rotation.y += 0.04

    // Cube033 movement
    cube033Ref.current.rotation.y += 0.04
  })


  return (
    <group {...props} dispose={null} scale={0.1} rotation={[0.2, -0.4, 0]} position={[-1, -0.2, 0]} >
      <directionalLight position={[-1.2, 1.2, 1]} color="#b7daed" intensity={3} />
      <group >
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['Metalic Black ']} position={[-9.184, 4.747, -4.195]} rotation={[-0.267, 0, -Math.PI / 2]} scale={[0.437, 2.993, 0.243]} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials['Metalic Black ']} position={[-2.09, 4.747, -4.195]} rotation={[-0.267, 0, -Math.PI / 2]} scale={[0.437, 2.993, 0.243]} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials['Metalic Black ']} position={[3.471, 4.747, -4.195]} rotation={[-0.267, 0, -Math.PI / 2]} scale={[0.437, 1.219, 0.243]} />
        <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['Purple Glow']} position={[-2.226, -9.635, 0.423]} rotation={[-0.267, 0, 0]} scale={[0.2, 2.941, 0.138]} />
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials['Metalic Black ']} position={[-6.236, -15.989, 2.21]} rotation={[-0.267, 0, -Math.PI / 2]} scale={[0.342, 3.326, 0.27]} />
        <group name="Cube057" position={[13.329, -14.712, 0.859]} rotation={[-0.267, 0, 0]} scale={[26.354, 9.722, 11.697]}>
          <mesh name="Cube058_1" geometry={nodes.Cube058_1.geometry} material={materials['Metalic Black ']} />
          <mesh name="Cube058_2" geometry={nodes.Cube058_2.geometry} material={materials['Phone Purple Part.001']} />
        </group>
        <mesh name="Circle011" geometry={nodes.Circle011.geometry} material={materials['Phone Purple Part.001']} position={[20.62, -17.329, 1.969]} rotation={[1.303, -0.02, -0.044]} scale={[0.349, 0.218, 0.218]} />
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials['Ash Graph']} position={[22.776, -12.156, 0.659]} rotation={[-0.267, 0, 0]} scale={[0.02, 2.962, 0.014]} />
        <group name="Circle" position={[18.747, -1.955, -1.52]} rotation={[1.303, 0, 0]} scale={[5.176, 2.547, 5.176]}>
          <mesh name="Circle015" geometry={nodes.Circle015.geometry} material={materials['Metalic Black ']} />
          <mesh name="Circle015_1" geometry={nodes.Circle015_1.geometry} material={materials['Phone Purple Part.001']} />
          <mesh name="Circle015_2" geometry={nodes.Circle015_2.geometry} material={materials['Super Dark Black']} />
          <mesh name="Circle015_3" geometry={nodes.Circle015_3.geometry} material={materials['Disk Black']} />
        </group>
        <group name="Circle001" position={[7.3, -1.955, -1.52]} rotation={[1.303, 0, 0]} scale={[5.176, 2.547, 5.176]}>
          <mesh name="Circle016" geometry={nodes.Circle016.geometry} material={materials['Metalic Black ']} />
          <mesh name="Circle016_1" geometry={nodes.Circle016_1.geometry} material={materials['Phone Purple Part.001']} />
          <mesh name="Circle016_2" geometry={nodes.Circle016_2.geometry} material={materials['Super Dark Black']} />
          <mesh name="Circle016_3" geometry={nodes.Circle016_3.geometry} material={materials['Disk Black']} />
        </group>
        <mesh ref={text005Ref} name="Text005" geometry={nodes.Text005.geometry} material={materials['Letters Material ']} position={[1.727, 15.736, 3.768]} rotation={[Math.PI / 2, 0, 0]} scale={[3.752, 1.113, 3.752]} />
        <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials['Super Dark Black']} position={[-10.086, 8.078, -5.271]} rotation={[1.303, 0, 0]} scale={0.583} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['Board Black']} position={[5.249, -5.228, -2.123]} rotation={[-0.267, 0, 0]} scale={[28.038, 19.082, 2.487]} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Board Black 2']} position={[5.433, 4.65, -4.544]} rotation={[-0.267, 0, 0]} scale={[40.625, 44.274, 17.265]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['Board Black']} position={[-6.27, -16.179, 1.867]} rotation={[-0.267, 0, 0]} scale={[20.039, 74.184, 15.965]} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['Board Black 2']} position={[-12.208, 0.553, -2.691]} rotation={[-0.267, 0, 0]} scale={[11.878, 25.576, 11.878]} />

      </group>

      <mesh ref={cube058Ref} name="Cube058" geometry={nodes.Cube058.geometry} material={materials['Round Box Glass']} position={[5.299, 16.843, 1.728]} scale={[11.605, 7.582, 41.75]} />
      <group ref={cube059Ref} name="Cube059" position={[5.299, 15.706, 1.728]} scale={[10.433, 4.787, 15.046]}>
        <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials['Box Material']} />
        <mesh name="Cube059_2" geometry={nodes.Cube059_2.geometry} material={materials['Purple Moles']} />
      </group>
      <mesh ref={cube032Ref} name="Cube032" geometry={nodes.Cube032.geometry} material={materials['Round Glasses']} position={[5.299, 16.76, 1.728]} scale={[12.502, 9.016, 53.297]} />
      <mesh ref={text007Ref} name="Text007" geometry={nodes.Text007.geometry} material={materials['Green Neon']} position={[-21.344, -7.846, 6.658]} rotation={[1.171, 0.444, -0.653]} scale={[6.302, 6.045, 6.612]} />
      <mesh ref={cube014Ref} name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Reflective Glass Material ']} position={[-24.227, 17.647, -0.177]} rotation={[-0.863, 0.439, 0.982]} scale={[53.479, 115.151, 53.479]} />
      <mesh ref={cube033Ref} name="Cube033" geometry={nodes.Cube033.geometry} material={materials['Reflective Glass Material ']} position={[-20.676, -7.231, 6.835]} rotation={[-0.517, 0.506, -2.088]} scale={[53.839, 115.928, 53.839]} />
    </group>
  )
}

useGLTF.preload('./models/about_hero.glb')
