/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/hero_cube.glb --k
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placeholder-cube-5-68052d2217874be99fc4aea7c02e94fa
Title: Placeholder-Cube 5
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function HeroCube(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/hero_cube.glb')
  console.log('This is the animations', animations)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const playAnimation = () => {
      actions['Animation'].reset().fadeIn(0.5).play()
    }

    // Call the playAnimation function once the component is mounted
    playAnimation()

    // Clean up the animation on component unmount
    // return () => {
    //   actions.stop()
    // }
  }, [])
  return (
    <group ref={group} {...props} dispose={null} scale={0.2}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_cell006_0" position={[0.608, -0.579, -0.729]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell_1" position={[0.89, -0.346, 0.714]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell002_2" position={[0.786, -0.891, -0.007]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell003_3" position={[0.487, -0.221, -0.173]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell004_4" position={[0.338, -0.192, -0.079]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell005_5" position={[0.456, 0.033, -0.143]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell006_6" position={[0.906, -0.498, -0.239]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell007_7" position={[0.763, -0.853, 0.755]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell009_8" position={[0.284, -0.691, 0.004]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell010_9" position={[0.999, -0.766, -0.527]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell011_10" position={[0.916, -0.141, 0.037]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell_11" position={[-0.677, 0.472, 0.742]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell001_12" position={[-0.304, 0.647, -0.186]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell002_13" position={[-0.773, -0.213, 0.673]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell003_14" position={[0.413, 0.065, -0.12]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell004_15" position={[-0.073, 0.83, 0.09]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell005_16" position={[0.254, 0.097, 0.841]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell007_17" position={[-0.187, 0.652, 0.692]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell009_18" position={[-0.126, 0.107, -0.487]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell010_19" position={[-0.1, -0.076, 0.867]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell011_20" position={[-0.681, 0.812, 0.249]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell_21" position={[-0.185, 0.144, -0.35]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell001_22" position={[-0.265, 0.293, 0.261]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell002_23" position={[-0.377, -0.332, 0.465]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell003_24" position={[-0.486, -0.282, 0.188]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell004_25" position={[-0.299, -0.266, 0.015]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell005_26" position={[0.069, 0.314, 0.08]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell006_27" position={[-0.045, -0.269, 0.309]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell007_28" position={[0.089, 0.08, 0.5]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell009_29" position={[0.159, 0.013, -0.094]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell010_30" position={[-0.35, 0.015, 0.538]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell008_cell011_31" position={[0.305, -0.073, 0.391]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell_32" position={[-0.814, -0.159, 0.106]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell001_33" position={[-0.6, -0.415, 0.205]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell002_34" position={[-0.867, 0.23, 0.391]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell004_35" position={[-0.568, 0.044, 0.377]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell005_36" position={[-0.736, 0.446, 0.109]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell006_37" position={[-0.974, 0.081, 0.177]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell007_38" position={[-0.697, -0.553, 0.135]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell008_39" position={[-0.57, 0.262, 0.447]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell009_40" position={[-0.733, 0.147, -0.187]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell001_cell006_cell011_41" position={[-0.555, -0.186, 0.057]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell_42" position={[0.588, -0.918, 0.514]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell001_43" position={[0.787, -0.07, 0.419]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell002_44" position={[0.491, -0.293, 0.96]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell003_45" position={[0.973, -0.515, 0.406]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell004_46" position={[0.593, -0.125, 0.574]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell005_47" position={[0.433, -0.297, 0.697]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell006_48" position={[0.311, -0.984, 0.584]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell007_49" position={[0.462, -0.312, 0.268]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell008_50" position={[0.739, -0.407, 0.453]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell009_51" position={[0.843, -0.746, 0.466]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell010_52" position={[0.457, -0.674, 0.741]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell004_cell008_cell011_53" position={[0.453, -0.755, 0.32]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell_54" position={[0.469, 0.201, -0.353]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell001_55" position={[0.868, 0.745, -0.638]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell002_56" position={[0.457, 0.808, -0.357]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell004_57" position={[0.849, 0.36, -0.398]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell005_58" position={[0.816, 0.212, -0.77]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell006_59" position={[0.493, 0.75, -0.728]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell007_60" position={[0.656, -0.084, -0.421]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell008_61" position={[0.35, 0.301, -0.849]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell007_cell010_62" position={[0.406, -0.069, -0.649]}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell_63" position={[0.789, 0.849, 0.688]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell001_64" position={[0.707, 0.29, 0.235]}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell002_65" position={[0.442, 0.867, -0.011]}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell003_66" position={[0.89, 0.508, 0.206]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell004_67" position={[0.642, 1, -0.246]} />
              <group name="Cube_cell005_cell005_68" position={[0.876, 0.373, 0.694]}>
                <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell006_69" position={[0.518, 0.717, 0.703]}>
                <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell007_70" position={[0.229, 0.988, -0.108]}>
                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell008_71" position={[0.78, 0.876, 0.163]}>
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell009_72" position={[0.405, 0.967, 0.292]}>
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell010_73" position={[0.51, 0.217, 0.834]}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell005_cell011_74" position={[0.669, 0.69, 0.428]} />
              <group name="Cube_cell003_cell_75" position={[-0.867, 0.855, -0.759]}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.cUBE} />
              </group>
              <group name="Cube_cell003_cell001_76" position={[-0.194, 0.413, -0.577]}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell003_77" position={[-0.653, 0.519, -0.812]}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell004_78" position={[-0.134, 0.448, -0.96]}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell005_79" position={[0.047, 0.999, -0.459]}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell006_80" position={[-0.972, 0.822, -0.293]}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell007_81" position={[-0.915, 0.445, -0.641]}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell008_82" position={[-0.679, 0.815, -0.305]}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell009_83" position={[-0.139, 0.831, -0.303]}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell010_84" position={[0.131, 0.943, -0.349]}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell003_cell011_85" position={[-0.214, 0.853, -0.703]}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell_86" position={[-0.028, -0.189, -0.402]}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell001_87" position={[-0.912, 0.015, -0.973]}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell002_88" position={[-0.945, -0.477, -0.59]}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell003_89" position={[-0.732, -0.468, -0.326]}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell004_90" position={[-0.53, -0.248, -0.787]}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell005_91" position={[-0.162, -0.773, -0.361]}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell006_92" position={[-0.838, -0.621, 0.024]}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell007_93" position={[0.041, -0.503, -0.857]}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell008_94" position={[-0.886, -0.152, -0.755]}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell009_95" position={[-0.708, -0.718, -0.817]}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell010_96" position={[-0.758, -0.842, -0.108]}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell002_cell011_97" position={[-0.166, 0.034, -0.848]}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell_98" position={[-0.507, -0.801, 0.882]}>
                <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell001_99" position={[0.062, -0.61, 0.113]}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell002_100" position={[-0.715, -0.46, 0.892]}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell003_101" position={[-0.718, -0.72, 0.507]}>
                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell005_102" position={[0.04, -0.856, 0.877]}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell006_103" position={[-0.163, -0.572, 0.856]}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_cell_cell007_104" position={[-0.139, -0.823, 0.499]}>
                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.material_0} />
              </group>
              <group name="Cube_105" position={[6, 0, 0]}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.material} />
                <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.Glass} />
              </group>
              <group name="Cube001_106" position={[0, 6, 0]}>
                <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.material} />
                <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.Glass} />
              </group>
              <group name="Cube002_107" position={[-6, 0, 0]}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.material} />
                <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.Glass} />
              </group>
              <group name="Cube003_108" position={[0, -6, 0]}>
                <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.material} />
                <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.Glass} />
              </group>
              <group name="Cube004_109" position={[0, 0, 6]}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.material} />
                <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.Glass} />
              </group>
              <group name="Cube005_110" position={[0, 0, -6]}>
                <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.material} />
                <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.Glass} />
              </group>
              <group name="Cube006_111" scale={14.737}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['2.001']} />
                <mesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials['Glass.001']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/hero_cube.glb')
