/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/shakira_laptop.glb --k
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'

export function Shakira(props) {
  const { animation } = props

  const { nodes, materials } = useGLTF('./models/shakira_laptop.glb')

  const group = useRef()

  const {animations: typingAnimation} = useFBX('./animations/TypingShakira.fbx')
  const {animations: standingAnimation} = useFBX('./animations/Idle.fbx')
  const {animations: walkingAnimation} = useFBX('./animations/WalkingCarryingShakira.fbx')

  typingAnimation[0].name = "Typing" 
  standingAnimation[0].name = "Standing" 
  walkingAnimation[0].name = "Walking" 

  const { actions } = useAnimations([typingAnimation[0], walkingAnimation[0], standingAnimation[0]], group)

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play()
    return () => {
      actions[animation].reset().fadeOut(0.5)
    }
  }, [animation])
 
  return (
    <group {...props} dispose={null}>
      <group name="Laptop" position={[-0.31, 1.228, 0.107]} rotation={[-Math.PI / 2, 0, 0]} scale={0.429}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="case_0" position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.speaker} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.body} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.black_plastic} />
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.touchpad} />
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.holes} />
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.ports} />
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.metal} />
          </group>
          <group name="lid_3" position={[0.498, 0.037, 0.667]} rotation={[1.806, 0, 0]} scale={0.281}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.body} />
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.display} />
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.touchscreen_bezel} />
            <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.black_plastic} />
          </group>
          <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.body} position={[0.496, 0, 0.454]} rotation={[1.544, 0, 0]} scale={[0.983, 0.941, 0.983]} />
        </group>
      </group>
      <mesh name="Logo" geometry={nodes.Logo.geometry} material={materials.LogoImage} position={[-0.1, 1.334, 0.437]} rotation={[1.817, 0, 0]} scale={[0.05, 0.053, 0.045]} />
      <group ref={group} >
        <primitive object={nodes.Hips} />
        <mesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} />
        <mesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} />
        <mesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} />
        <mesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} />
        <mesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} />
        <mesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} />
        <mesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} />
        <mesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} />
        <mesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} />
      </group>
      
    </group>
  )
}

useGLTF.preload('./models/shakira_laptop.glb')
